const KEY='halloumi-empire-v0-save-1';
const keys=['farm','dairy','grill'];
const costs={farm:12,dairy:18,grill:24};
const autoCosts={farm:40,dairy:80,grill:120};
const cycles={farm:2.5,dairy:3,grill:3.5};
const empty=()=>({coins:0,milk:0,halloumi:0,levels:{farm:1,dairy:1,grill:1},auto:{farm:false,dairy:false,grill:false},progress:{farm:0,dairy:0,grill:0},sold:0,taps:0,firstSale:false,lastUpdatedAt:Date.now()});
const $=id=>document.getElementById(id);
const fmt=n=>Math.floor(n).toLocaleString('fr-FR');
const cost=k=>Math.ceil(costs[k]*1.38**(s.levels[k]-1));
const price=()=>8+(s.levels.grill-1)*3;
function load(){try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(!saved?.levels||!saved?.auto)return empty();const clean=empty();for(const k of ['coins','milk','halloumi','sold','taps','lastUpdatedAt'])if(Number.isFinite(saved[k])&&saved[k]>=0)clean[k]=saved[k];clean.firstSale=saved.firstSale===true||clean.sold>0;for(const k of keys){if(Number.isInteger(saved.levels[k])&&saved.levels[k]>=1&&saved.levels[k]<=1000)clean.levels[k]=saved.levels[k];clean.auto[k]=saved.auto[k]===true;if(Number.isFinite(saved.progress?.[k])&&saved.progress[k]>=0&&saved.progress[k]<cycles[k])clean.progress[k]=saved.progress[k]}return clean}catch{return empty()}}
let s=load(),lastTick=Date.now(),savedAt=lastTick,noticeTimer;
function save(t=Date.now()){s.lastUpdatedAt=t;try{localStorage.setItem(KEY,JSON.stringify(s))}catch{}savedAt=t}
function sell(n){s.halloumi-=n;s.coins+=n*price();s.sold+=n;s.firstSale=true}
function advance(dt){if(s.auto.farm){s.progress.farm+=dt;const batches=Math.floor(s.progress.farm/cycles.farm);if(batches){s.milk+=batches*s.levels.farm;s.progress.farm-=batches*cycles.farm}}if(s.auto.dairy){s.progress.dairy=Math.min(cycles.dairy,s.progress.dairy+dt);if(s.milk>=1&&s.progress.dairy>=cycles.dairy){const n=Math.min(s.milk,s.levels.dairy);s.milk-=n;s.halloumi+=n;s.progress.dairy=0}}if(s.auto.grill){s.progress.grill=Math.min(cycles.grill,s.progress.grill+dt);if(s.halloumi>=1&&s.progress.grill>=cycles.grill){sell(Math.min(s.halloumi,s.levels.grill));s.progress.grill=0}}}
function catchUp(now){const seconds=Math.min(14400,Math.max(0,(now-s.lastUpdatedAt)/1000)),before=s.coins;const full=Math.floor(seconds);for(let i=0;i<full;i++)advance(1);if(seconds-full)advance(seconds-full);lastTick=now;save(now);if(seconds>=10&&s.coins>before)notify(`Pendant ton absence : +${fmt(s.coins-before)} pièces !`)}
function notify(msg){const box=$('notice');box.textContent=msg;box.hidden=false;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>box.hidden=true,4000)}
function sparkle(k,text){const b=$('scene-'+k),f=$('float');b.classList.remove('active','pop');f.classList.remove('fly');void b.offsetWidth;b.classList.add('active','pop');f.textContent=text;f.classList.add('fly');setTimeout(()=>{b.classList.remove('active','pop');f.classList.remove('fly')},1100)}
function objective(){if(!s.firstSale)return'Trais une chèvre, fabrique un bloc et vends-le !';if(!s.auto.farm)return'Automatise la ferme : elle produira du lait toute seule.';if(!s.auto.dairy)return'Automatise la fromagerie.';if(!s.auto.grill)return'Automatise le grill et laisse tourner ton île.';if(s.sold<100)return`Vends 100 halloumis : encore ${fmt(100-s.sold)} !`;return'Bravo ! Améliore tes bâtiments pour agrandir ton empire.'}
function render(){ $('coins').textContent=fmt(s.coins);$('milk').textContent=fmt(s.milk);$('halloumi').textContent=fmt(s.halloumi);$('price').textContent=fmt(price());$('objective').textContent=objective();$('income').textContent=s.auto.grill?`Jusqu’à ${fmt(60/cycles.grill*s.levels.grill*price())} 🪙/min`:'Vente manuelle';$('stage').textContent=s.auto.grill?'Empire en marche':s.auto.farm?'Une ferme qui grandit':'Les débuts';for(const k of keys){$('scene-'+k).classList.toggle('automated',s.auto[k]);$(k+'-level').textContent=`NV. ${s.levels[k]}`;const up=document.querySelector(`[data-upgrade="${k}"]`);up.textContent=`Améliorer · ${fmt(cost(k))} 🪙`;up.disabled=s.coins<cost(k);const auto=document.querySelector(`[data-auto="${k}"]`);auto.textContent=s.auto[k]?'✓ Automatique':`⚙️ Automatiser · ${fmt(autoCosts[k])} 🪙`;auto.disabled=s.auto[k]||s.coins<autoCosts[k];auto.classList.toggle('done',s.auto[k]);const manual=document.querySelector(`[data-manual="${k}"]`),n=k==='farm'?s.levels.farm:Math.min(s[k==='dairy'?'milk':'halloumi'],s.levels[k]);manual.disabled=k!=='farm'&&n<1;manual.textContent=k==='farm'?`Traire +${n} 🥛`:k==='dairy'?`Fabriquer · ${n} 🥛`:`Vendre · +${n*price()} 🪙`}
const ms=[[s.firstSale,'Premier halloumi vendu'],[s.auto.farm,'Ferme automatisée'],[s.auto.dairy,'Fromagerie automatisée'],[s.auto.grill,'Grill automatisé'],[s.sold>=100,'100 halloumis vendus']];$('milestones').replaceChildren(...ms.map(([done,name])=>{const d=document.createElement('div');d.className='milestone'+(done?' complete':'');d.textContent=(done?'✓ ':'○ ')+name;return d}));$('stats').textContent=`${fmt(s.sold)} blocs vendus · ${fmt(s.taps)} actions manuelles`}
document.addEventListener('click',e=>{const btn=e.target.closest('button');if(!btn||btn.disabled)return;let fx=null;const k=btn.dataset.manual;if(k){if(k==='farm'){s.milk+=s.levels.farm;fx=['farm',`+${s.levels.farm} 🥛`]}else if(k==='dairy'&&s.milk>=1){const n=Math.min(s.milk,s.levels.dairy);s.milk-=n;s.halloumi+=n;fx=['dairy',`+${n} 🧀`]}else if(k==='grill'&&s.halloumi>=1){const n=Math.min(s.halloumi,s.levels.grill);sell(n);fx=['grill',`+${n*price()} 🪙`]}s.taps++}const up=btn.dataset.upgrade;if(up&&s.coins>=cost(up)){s.coins-=cost(up);s.levels[up]++;fx=[up,'NIVEAU +1 !'];notify('Bâtiment amélioré !')}const auto=btn.dataset.auto;if(auto&&!s.auto[auto]&&s.coins>=autoCosts[auto]){s.coins-=autoCosts[auto];s.auto[auto]=true;fx=[auto,'AUTO !'];notify('Automatisation débloquée !')}if(btn.id==='reset'&&window.confirm('Effacer ta partie et recommencer ?')){s=empty();notify('Nouvelle partie commencée !')}if(fx)sparkle(...fx);save();render()});
catchUp(Date.now());render();setInterval(()=>{if(document.hidden)return;const now=Date.now(),dt=Math.max(0,Math.min(14400,(now-lastTick)/1000));lastTick=now;if(dt>3)catchUp(now);else{advance(dt);if(now-savedAt>=3000)save(now)}render()},250);document.addEventListener('visibilitychange',()=>{if(document.hidden)save();else{catchUp(Date.now());render()}});window.addEventListener('pagehide',()=>save());
