const KEY='halloumi-empire-v0-save-1', K=['farm','dairy','grill'];
const COST={farm:12,dairy:18,grill:24},HIRE={farm:16,dairy:32,grill:48},CYCLE={farm:2.5,dairy:3,grill:3.5},NAME={farm:'Ferme',dairy:'Atelier',grill:'Grill'};
const $=id=>document.getElementById(id),fmt=n=>Math.floor(n).toLocaleString('fr-FR');
const fresh=()=>({coins:0,milk:0,halloumi:0,levels:{farm:1,dairy:1,grill:1},auto:{farm:false,dairy:false,grill:false},progress:{farm:0,dairy:0,grill:0},sold:0,taps:0,firstSale:false,lastUpdatedAt:Date.now()});
function load(){try{let old=JSON.parse(localStorage.getItem(KEY)||'null');if(!old?.levels||!old?.auto)return fresh();let s=fresh();for(let key of ['coins','milk','halloumi','sold','taps','lastUpdatedAt'])if(Number.isFinite(old[key])&&old[key]>=0)s[key]=old[key];s.firstSale=old.firstSale===true||s.sold>0;for(let k of K){if(Number.isInteger(old.levels[k])&&old.levels[k]>=1&&old.levels[k]<=1000)s.levels[k]=old.levels[k];s.auto[k]=old.auto[k]===true;if(Number.isFinite(old.progress?.[k])&&old.progress[k]>=0)s.progress[k]=Math.min(old.progress[k],CYCLE[k])}return s}catch{return fresh()}}
let s=load(),lastTick=Date.now(),lastSaved=lastTick,selected=null,tabName='island',toastTimer;
let previous={milk:s.milk,halloumi:s.halloumi,sold:s.sold};
const price=()=>8+(s.levels.grill-1)*3;
const upCost=k=>Math.ceil(COST[k]*1.38**(s.levels[k]-1));
const cycle=k=>CYCLE[k]/(1+Math.floor((s.levels[k]-1)/5)*.12);
function save(now=Date.now()){s.lastUpdatedAt=now;try{localStorage.setItem(KEY,JSON.stringify(s))}catch{}lastSaved=now}
function notify(text){let e=$('toast');e.textContent=text;e.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.hidden=true,3200)}
function sell(n){s.halloumi-=n;s.coins+=n*price();s.sold+=n;s.firstSale=true}
function advance(dt){if(s.auto.farm){s.progress.farm+=dt;let n=Math.floor(s.progress.farm/cycle('farm'));if(n){s.milk+=n*s.levels.farm;s.progress.farm-=n*cycle('farm')}}if(s.auto.dairy){s.progress.dairy=Math.min(cycle('dairy'),s.progress.dairy+dt);if(s.milk>0&&s.progress.dairy>=cycle('dairy')){let n=Math.min(s.milk,s.levels.dairy);s.milk-=n;s.halloumi+=n;s.progress.dairy=0}}if(s.auto.grill){s.progress.grill=Math.min(cycle('grill'),s.progress.grill+dt);if(s.halloumi>0&&s.progress.grill>=cycle('grill')){sell(Math.min(s.halloumi,s.levels.grill));s.progress.grill=0}}}
function catchUp(now){let seconds=Math.min(14400,Math.max(0,(now-s.lastUpdatedAt)/1000)),coins=s.coins,sold=s.sold,n=Math.floor(seconds);for(let i=0;i<n;i++)advance(1);if(seconds-n)advance(seconds-n);lastTick=now;save(now);previous={milk:s.milk,halloumi:s.halloumi,sold:s.sold};if(seconds>=10&&s.coins>coins){$('offline-detail').textContent=`${fmt(s.sold-sold)} bloc(s) vendus pendant ton absence`;$('offline-coins').textContent=`+${fmt(s.coins-coins)} pièces`;$('offline-overlay').hidden=false}}
function mission(){if(!s.firstSale)return'Trais, fabrique, puis vends un bloc !';if(!s.auto.farm)return'Touche la ferme et recrute une fermière.';if(!s.auto.dairy)return'Touche l’atelier et recrute un fromager.';if(!s.auto.grill)return'Touche le grill et recrute un cuisinier.';if(s.sold<100)return`Encore ${fmt(100-s.sold)} ventes avant 100 blocs !`;return'Ton empire tourne : améliore le poste le plus lent !'}
function bottleneck(){if(!s.auto.farm)return'Priorité : recruter une fermière.';if(!s.auto.dairy)return'Priorité : automatiser l’atelier.';if(!s.auto.grill)return'Priorité : automatiser le grill.';if(s.milk===0&&s.halloumi===0)return'Manque de lait : améliore la ferme.';if(s.milk>s.halloumi+6)return'Le lait s’accumule : améliore l’atelier.';if(s.halloumi>6)return'Le halloumi s’accumule : améliore le grill.';return'Chaîne équilibrée : augmente le rendement du poste le moins avancé.'}
function animate(id,name,text){let e=$(id);e.classList.remove(name);void e.offsetWidth;if(text!==undefined)e.textContent=text;e.classList.add(name)}
function sheet(){if(!selected)return;let k=selected;$('sheet-title').textContent=NAME[k];$('sheet-level').textContent=fmt(s.levels[k]);$('sheet-output').textContent=k==='grill'?`${price()} pièces / bloc`:`${s.levels[k]} ${k==='farm'?'lait':'bloc(s)'} / cycle`;$('sheet-status').textContent=s.auto[k]?`Employé recruté · 1 cycle toutes les ${cycle(k).toFixed(1)} s`:'Production manuelle : recrute un employé pour automatiser.';let up=$('upgrade'),hire=$('automate');up.textContent=`Améliorer · ${fmt(upCost(k))} pièces`;up.disabled=s.coins<upCost(k);$('upgrade-preview').textContent=k==='grill'?`Prochain niveau : ${price()+3} pièces par bloc.`:`Prochain niveau : ${s.levels[k]+1} par cycle.`;hire.textContent=s.auto[k]?'✓ Employé recruté':`Recruter · ${HIRE[k]} pièces`;hire.disabled=s.auto[k]||s.coins<HIRE[k]}
function render(){$('coins').textContent=fmt(s.coins);$('milk').textContent=fmt(s.milk);$('halloumi').textContent=fmt(s.halloumi);$('price').textContent=fmt(price());$('sold').textContent=fmt(s.sold);$('taps').textContent=fmt(s.taps);$('objective').textContent=mission();$('bottleneck').textContent=bottleneck();$('income').textContent=s.auto.grill?`≤ ${fmt(60/cycle('grill')*s.levels.grill*price())}/min`:'0/min';$('farm-quick').textContent=`+${s.levels.farm} lait`;$('dairy-quick').textContent=`${Math.min(s.milk,s.levels.dairy)} lait`;$('grill-quick').textContent=`+${Math.min(s.halloumi,s.levels.grill)*price()} pièces`;for(let k of K){$(k+'-level').textContent=`Niv. ${fmt(s.levels[k])}`;$(k+'-worker').hidden=!s.auto[k];let btn=document.querySelector(`[data-manual="${k}"]`);btn.disabled=k==='dairy'?s.milk<1:k==='grill'?s.halloumi<1:false}let steps=[[s.firstSale,'Premier bloc vendu'],[s.auto.farm,'Ferme automatisée'],[s.auto.dairy,'Atelier automatisé'],[s.auto.grill,'Grill automatisé'],[s.sold>=100,'100 blocs vendus']];$('milestones').replaceChildren(...steps.map(([done,label])=>{let d=document.createElement('div');d.className='achievement'+(done?' complete':'');d.textContent=`${done?'✦':'○'}  ${label}`;return d}));sheet()}
function open(k){selected=k;sheet();$('station-overlay').hidden=false;$('close-sheet').focus()}
function close(){$('station-overlay').hidden=true;selected=null}
function switchTab(name){tabName=name;for(let k of ['island','achievements','empire'])$('screen-'+k).hidden=k!==name;for(let b of document.querySelectorAll('[data-tab]')){let active=b.dataset.tab===name;b.classList.toggle('selected',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')}}
document.addEventListener('click',e=>{let b=e.target.closest('button');if(b?.dataset.tab){switchTab(b.dataset.tab);return}if(b?.id==='collect'){$('offline-overlay').hidden=true;lastTick=Date.now();save(lastTick);return}if(b?.id==='close-sheet'||b?.id==='close-scrim'){close();return}if(b?.id==='reset'){if(!window.confirm('Effacer ta partie et recommencer ?'))return;s=fresh();previous={milk:0,halloumi:0,sold:0};close();switchTab('island');save();render();notify('Nouvelle partie !');return}if(b?.id==='upgrade'&&selected){let k=selected;if(s.coins<upCost(k))return;s.coins-=upCost(k);s.levels[k]++;save();render();notify(`${NAME[k]} amélioré !`);return}if(b?.id==='automate'&&selected){let k=selected;if(s.auto[k]||s.coins<HIRE[k])return;s.coins-=HIRE[k];s.auto[k]=true;save();render();notify(`Employé recruté : ${NAME[k]} automatique !`);return}if(b?.dataset.manual){let k=b.dataset.manual;if(k==='farm'){s.milk+=s.levels.farm;animate('milk-cargo','travel');animate('burst','fly',`+${s.levels.farm} lait`)}else if(k==='dairy'&&s.milk){let n=Math.min(s.milk,s.levels.dairy);s.milk-=n;s.halloumi+=n;animate('halloumi-cargo','travel');animate('burst','fly',`+${n} halloumi`)}else if(k==='grill'&&s.halloumi){let n=Math.min(s.halloumi,s.levels.grill);sell(n);animate('burst','fly',`+${n*price()} pièces`)}else return;s.taps++;previous={milk:s.milk,halloumi:s.halloumi,sold:s.sold};save();render();return}if(!$('station-overlay').hidden)return;let zone=e.target.closest('[data-open]');if(zone&&tabName==='island')open(zone.dataset.open)});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('station-overlay').hidden)close();if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-open]')){e.preventDefault();open(e.target.dataset.open)}});
catchUp(Date.now());render();switchTab('island');setInterval(()=>{if(document.hidden||!$('offline-overlay').hidden)return;let now=Date.now(),dt=Math.max(0,Math.min(14400,(now-lastTick)/1000));lastTick=now;if(dt>3){catchUp(now);render();return}advance(dt);if(tabName==='island'&&$('station-overlay').hidden){if(s.milk>previous.milk)animate('milk-cargo','travel');if(s.halloumi>previous.halloumi)animate('halloumi-cargo','travel');if(s.sold>previous.sold)animate('burst','fly',`+${(s.sold-previous.sold)*price()} pièces`)}previous={milk:s.milk,halloumi:s.halloumi,sold:s.sold};if(now-lastSaved>=3000)save(now);render()},250);
document.addEventListener('visibilitychange',()=>{if(document.hidden)save();else{catchUp(Date.now());render()}});window.addEventListener('pagehide',()=>save());
